# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commander_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_pb2 as std__pb2
import labust_pb2 as labust__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='commander_service.proto',
  package='service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x63ommander_service.proto\x12\x07service\x1a\tstd.proto\x1a\x0clabust.proto\"+\n\x18PrimitivePointerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x65\n\tCommander\x12X\n\x10PrimitivePointer\x12\x1f.labust.PointerPrimitiveService\x1a!.service.PrimitivePointerResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[std__pb2.DESCRIPTOR,labust__pb2.DESCRIPTOR,])




_PRIMITIVEPOINTERRESPONSE = _descriptor.Descriptor(
  name='PrimitivePointerResponse',
  full_name='service.PrimitivePointerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='service.PrimitivePointerResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['PrimitivePointerResponse'] = _PRIMITIVEPOINTERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrimitivePointerResponse = _reflection.GeneratedProtocolMessageType('PrimitivePointerResponse', (_message.Message,), dict(
  DESCRIPTOR = _PRIMITIVEPOINTERRESPONSE,
  __module__ = 'commander_service_pb2'
  # @@protoc_insertion_point(class_scope:service.PrimitivePointerResponse)
  ))
_sym_db.RegisterMessage(PrimitivePointerResponse)



_COMMANDER = _descriptor.ServiceDescriptor(
  name='Commander',
  full_name='service.Commander',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='PrimitivePointer',
    full_name='service.Commander.PrimitivePointer',
    index=0,
    containing_service=None,
    input_type=labust__pb2._POINTERPRIMITIVESERVICE,
    output_type=_PRIMITIVEPOINTERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMANDER)

DESCRIPTOR.services_by_name['Commander'] = _COMMANDER

# @@protoc_insertion_point(module_scope)
