# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_pb2 as std__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geometry.proto',
  package='geometry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0egeometry.proto\x12\x08geometry\x1a\tstd.proto\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"N\n\x05Twist\x12!\n\x06linear\x18\x01 \x01(\x0b\x32\x11.geometry.Vector3\x12\"\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x11.geometry.Vector3\"T\n\x04Pose\x12!\n\x08position\x18\x01 \x01(\x0b\x32\x0f.geometry.Point\x12)\n\x0borientation\x18\x02 \x01(\x0b\x32\x14.geometry.Quaternion\"M\n\x06Wrench\x12 \n\x05\x66orce\x18\x01 \x01(\x0b\x32\x11.geometry.Vector3\x12!\n\x06torque\x18\x02 \x01(\x0b\x32\x11.geometry.Vector3\"F\n\x12PoseWithCovariance\x12\x1c\n\x04pose\x18\x01 \x01(\x0b\x32\x0e.geometry.Pose\x12\x12\n\ncovariance\x18\x02 \x03(\x01\"d\n\x19PoseWithCovarianceStamped\x12\x1b\n\x06header\x18\x01 \x01(\x0b\x32\x0b.std.Header\x12*\n\x04pose\x18\x02 \x01(\x0b\x32\x1c.geometry.PoseWithCovariance\"I\n\x13TwistWithCovariance\x12\x1e\n\x05twist\x18\x01 \x01(\x0b\x32\x0f.geometry.Twist\x12\x12\n\ncovariance\x18\x02 \x03(\x01\"g\n\x1aTwistWithCovarianceStamped\x12\x1b\n\x06header\x18\x01 \x01(\x0b\x32\x0b.std.Header\x12,\n\x05twist\x18\x02 \x01(\x0b\x32\x1d.geometry.TwistWithCovarianceb\x06proto3')
  ,
  dependencies=[std__pb2.DESCRIPTOR,])




_VECTOR3 = _descriptor.Descriptor(
  name='Vector3',
  full_name='geometry.Vector3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='geometry.Vector3.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='geometry.Vector3.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='geometry.Vector3.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=81,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='geometry.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='geometry.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='geometry.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='geometry.Point.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=123,
)


_QUATERNION = _descriptor.Descriptor(
  name='Quaternion',
  full_name='geometry.Quaternion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='geometry.Quaternion.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='geometry.Quaternion.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='geometry.Quaternion.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='geometry.Quaternion.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=181,
)


_TWIST = _descriptor.Descriptor(
  name='Twist',
  full_name='geometry.Twist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear', full_name='geometry.Twist.linear', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular', full_name='geometry.Twist.angular', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=261,
)


_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='geometry.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='geometry.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='geometry.Pose.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=347,
)


_WRENCH = _descriptor.Descriptor(
  name='Wrench',
  full_name='geometry.Wrench',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='force', full_name='geometry.Wrench.force', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque', full_name='geometry.Wrench.torque', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=426,
)


_POSEWITHCOVARIANCE = _descriptor.Descriptor(
  name='PoseWithCovariance',
  full_name='geometry.PoseWithCovariance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='geometry.PoseWithCovariance.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='geometry.PoseWithCovariance.covariance', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=498,
)


_POSEWITHCOVARIANCESTAMPED = _descriptor.Descriptor(
  name='PoseWithCovarianceStamped',
  full_name='geometry.PoseWithCovarianceStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='geometry.PoseWithCovarianceStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='geometry.PoseWithCovarianceStamped.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=600,
)


_TWISTWITHCOVARIANCE = _descriptor.Descriptor(
  name='TwistWithCovariance',
  full_name='geometry.TwistWithCovariance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='twist', full_name='geometry.TwistWithCovariance.twist', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='geometry.TwistWithCovariance.covariance', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=602,
  serialized_end=675,
)


_TWISTWITHCOVARIANCESTAMPED = _descriptor.Descriptor(
  name='TwistWithCovarianceStamped',
  full_name='geometry.TwistWithCovarianceStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='geometry.TwistWithCovarianceStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='twist', full_name='geometry.TwistWithCovarianceStamped.twist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=677,
  serialized_end=780,
)

_TWIST.fields_by_name['linear'].message_type = _VECTOR3
_TWIST.fields_by_name['angular'].message_type = _VECTOR3
_POSE.fields_by_name['position'].message_type = _POINT
_POSE.fields_by_name['orientation'].message_type = _QUATERNION
_WRENCH.fields_by_name['force'].message_type = _VECTOR3
_WRENCH.fields_by_name['torque'].message_type = _VECTOR3
_POSEWITHCOVARIANCE.fields_by_name['pose'].message_type = _POSE
_POSEWITHCOVARIANCESTAMPED.fields_by_name['header'].message_type = std__pb2._HEADER
_POSEWITHCOVARIANCESTAMPED.fields_by_name['pose'].message_type = _POSEWITHCOVARIANCE
_TWISTWITHCOVARIANCE.fields_by_name['twist'].message_type = _TWIST
_TWISTWITHCOVARIANCESTAMPED.fields_by_name['header'].message_type = std__pb2._HEADER
_TWISTWITHCOVARIANCESTAMPED.fields_by_name['twist'].message_type = _TWISTWITHCOVARIANCE
DESCRIPTOR.message_types_by_name['Vector3'] = _VECTOR3
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Quaternion'] = _QUATERNION
DESCRIPTOR.message_types_by_name['Twist'] = _TWIST
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['Wrench'] = _WRENCH
DESCRIPTOR.message_types_by_name['PoseWithCovariance'] = _POSEWITHCOVARIANCE
DESCRIPTOR.message_types_by_name['PoseWithCovarianceStamped'] = _POSEWITHCOVARIANCESTAMPED
DESCRIPTOR.message_types_by_name['TwistWithCovariance'] = _TWISTWITHCOVARIANCE
DESCRIPTOR.message_types_by_name['TwistWithCovarianceStamped'] = _TWISTWITHCOVARIANCESTAMPED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.Vector3)
  ))
_sym_db.RegisterMessage(Vector3)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.Point)
  ))
_sym_db.RegisterMessage(Point)

Quaternion = _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNION,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.Quaternion)
  ))
_sym_db.RegisterMessage(Quaternion)

Twist = _reflection.GeneratedProtocolMessageType('Twist', (_message.Message,), dict(
  DESCRIPTOR = _TWIST,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.Twist)
  ))
_sym_db.RegisterMessage(Twist)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.Pose)
  ))
_sym_db.RegisterMessage(Pose)

Wrench = _reflection.GeneratedProtocolMessageType('Wrench', (_message.Message,), dict(
  DESCRIPTOR = _WRENCH,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.Wrench)
  ))
_sym_db.RegisterMessage(Wrench)

PoseWithCovariance = _reflection.GeneratedProtocolMessageType('PoseWithCovariance', (_message.Message,), dict(
  DESCRIPTOR = _POSEWITHCOVARIANCE,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.PoseWithCovariance)
  ))
_sym_db.RegisterMessage(PoseWithCovariance)

PoseWithCovarianceStamped = _reflection.GeneratedProtocolMessageType('PoseWithCovarianceStamped', (_message.Message,), dict(
  DESCRIPTOR = _POSEWITHCOVARIANCESTAMPED,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.PoseWithCovarianceStamped)
  ))
_sym_db.RegisterMessage(PoseWithCovarianceStamped)

TwistWithCovariance = _reflection.GeneratedProtocolMessageType('TwistWithCovariance', (_message.Message,), dict(
  DESCRIPTOR = _TWISTWITHCOVARIANCE,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.TwistWithCovariance)
  ))
_sym_db.RegisterMessage(TwistWithCovariance)

TwistWithCovarianceStamped = _reflection.GeneratedProtocolMessageType('TwistWithCovarianceStamped', (_message.Message,), dict(
  DESCRIPTOR = _TWISTWITHCOVARIANCESTAMPED,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:geometry.TwistWithCovarianceStamped)
  ))
_sym_db.RegisterMessage(TwistWithCovarianceStamped)


# @@protoc_insertion_point(module_scope)
