# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_pb2 as std__pb2
import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tf.proto',
  package='tf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08tf.proto\x12\x02tf\x1a\tstd.proto\x1a\x0egeometry.proto\"7\n\x0eTfFrameRequest\x12\x0f\n\x07\x66rameId\x18\x01 \x01(\t\x12\x14\n\x0c\x63hildFrameId\x18\x02 \x01(\t\"\xae\x01\n\x07TfFrame\x12\x1b\n\x06header\x18\x01 \x01(\x0b\x32\x0b.std.Header\x12\x0f\n\x07\x66rameId\x18\x02 \x01(\t\x12\x14\n\x0c\x63hildFrameId\x18\x03 \x01(\t\x12&\n\x0btranslation\x18\x04 \x01(\x0b\x32\x11.geometry.Vector3\x12&\n\x08rotation\x18\x05 \x01(\x0b\x32\x14.geometry.Quaternion\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\"*\n\x0bTfFrameList\x12\x1b\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x0b.tf.TfFrame2\xf7\x01\n\x02Tf\x12-\n\x0cGetAllFrames\x12\n.std.Empty\x1a\x0f.tf.TfFrameList\"\x00\x12-\n\x08GetFrame\x12\x12.tf.TfFrameRequest\x1a\x0b.tf.TfFrame\"\x00\x12\x32\n\x0fStreamAllFrames\x12\n.std.Empty\x1a\x0f.tf.TfFrameList\"\x00\x30\x01\x12\x32\n\x0bStreamFrame\x12\x12.tf.TfFrameRequest\x1a\x0b.tf.TfFrame\"\x00\x30\x01\x12+\n\x0cPublishFrame\x12\x0b.tf.TfFrame\x1a\n.std.Empty\"\x00(\x01\x62\x06proto3')
  ,
  dependencies=[std__pb2.DESCRIPTOR,geometry__pb2.DESCRIPTOR,])




_TFFRAMEREQUEST = _descriptor.Descriptor(
  name='TfFrameRequest',
  full_name='tf.TfFrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameId', full_name='tf.TfFrameRequest.frameId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='childFrameId', full_name='tf.TfFrameRequest.childFrameId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=98,
)


_TFFRAME = _descriptor.Descriptor(
  name='TfFrame',
  full_name='tf.TfFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tf.TfFrame.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frameId', full_name='tf.TfFrame.frameId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='childFrameId', full_name='tf.TfFrame.childFrameId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation', full_name='tf.TfFrame.translation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='tf.TfFrame.rotation', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='tf.TfFrame.address', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=275,
)


_TFFRAMELIST = _descriptor.Descriptor(
  name='TfFrameList',
  full_name='tf.TfFrameList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='tf.TfFrameList.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=319,
)

_TFFRAME.fields_by_name['header'].message_type = std__pb2._HEADER
_TFFRAME.fields_by_name['translation'].message_type = geometry__pb2._VECTOR3
_TFFRAME.fields_by_name['rotation'].message_type = geometry__pb2._QUATERNION
_TFFRAMELIST.fields_by_name['frames'].message_type = _TFFRAME
DESCRIPTOR.message_types_by_name['TfFrameRequest'] = _TFFRAMEREQUEST
DESCRIPTOR.message_types_by_name['TfFrame'] = _TFFRAME
DESCRIPTOR.message_types_by_name['TfFrameList'] = _TFFRAMELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TfFrameRequest = _reflection.GeneratedProtocolMessageType('TfFrameRequest', (_message.Message,), dict(
  DESCRIPTOR = _TFFRAMEREQUEST,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:tf.TfFrameRequest)
  ))
_sym_db.RegisterMessage(TfFrameRequest)

TfFrame = _reflection.GeneratedProtocolMessageType('TfFrame', (_message.Message,), dict(
  DESCRIPTOR = _TFFRAME,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:tf.TfFrame)
  ))
_sym_db.RegisterMessage(TfFrame)

TfFrameList = _reflection.GeneratedProtocolMessageType('TfFrameList', (_message.Message,), dict(
  DESCRIPTOR = _TFFRAMELIST,
  __module__ = 'tf_pb2'
  # @@protoc_insertion_point(class_scope:tf.TfFrameList)
  ))
_sym_db.RegisterMessage(TfFrameList)



_TF = _descriptor.ServiceDescriptor(
  name='Tf',
  full_name='tf.Tf',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=322,
  serialized_end=569,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllFrames',
    full_name='tf.Tf.GetAllFrames',
    index=0,
    containing_service=None,
    input_type=std__pb2._EMPTY,
    output_type=_TFFRAMELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFrame',
    full_name='tf.Tf.GetFrame',
    index=1,
    containing_service=None,
    input_type=_TFFRAMEREQUEST,
    output_type=_TFFRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamAllFrames',
    full_name='tf.Tf.StreamAllFrames',
    index=2,
    containing_service=None,
    input_type=std__pb2._EMPTY,
    output_type=_TFFRAMELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamFrame',
    full_name='tf.Tf.StreamFrame',
    index=3,
    containing_service=None,
    input_type=_TFFRAMEREQUEST,
    output_type=_TFFRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PublishFrame',
    full_name='tf.Tf.PublishFrame',
    index=4,
    containing_service=None,
    input_type=_TFFRAME,
    output_type=std__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TF)

DESCRIPTOR.services_by_name['Tf'] = _TF

# @@protoc_insertion_point(module_scope)
