# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import visualization_pb2 as visualization__pb2


class VisualizationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetMarker = channel.unary_stream(
        '/visualization.Visualization/SetMarker',
        request_serializer=visualization__pb2.MarkerRequest.SerializeToString,
        response_deserializer=visualization__pb2.Marker.FromString,
        )
    self.SetMarkerArray = channel.unary_stream(
        '/visualization.Visualization/SetMarkerArray',
        request_serializer=visualization__pb2.MarkerRequest.SerializeToString,
        response_deserializer=visualization__pb2.MarkerArray.FromString,
        )


class VisualizationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SetMarker(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMarkerArray(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VisualizationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetMarker': grpc.unary_stream_rpc_method_handler(
          servicer.SetMarker,
          request_deserializer=visualization__pb2.MarkerRequest.FromString,
          response_serializer=visualization__pb2.Marker.SerializeToString,
      ),
      'SetMarkerArray': grpc.unary_stream_rpc_method_handler(
          servicer.SetMarkerArray,
          request_deserializer=visualization__pb2.MarkerRequest.FromString,
          response_serializer=visualization__pb2.MarkerArray.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'visualization.Visualization', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
